sources:
  # Collect local system logs.
  macos_logs:
    type: file
    include: /var/log/system.log
    transforms:
      - type: static_fields
        fields:
          falcon.admin: <my name here>
    sink: macos-ngsiem


sinks:
  macos-ngsiem:
    type: hec
    token: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    url: https://ABCDEFGHIJKLMNOPQRSTUVWXYZ.ingest.us-1.crowdstrike.com
